# Generated by Django 3.2.5 on 2021-07-17 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effectivity', models.DateTimeField(verbose_name='Effectivity')),
                ('years_to_pay', models.IntegerField(verbose_name='Years to pay')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Base Amount')),
                ('interest_rate', models.FloatField(verbose_name='Interest Rate')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total Amount')),
                ('monthly', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Monthly')),
            ],
            options={
                'verbose_name': 'loan',
                'verbose_name_plural': 'loans',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Amount')),
                ('paydate', models.DateTimeField(auto_now_add=True, verbose_name='Payment Date')),
                ('loan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loan.loan', verbose_name='Loan')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=200, verbose_name='Unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'member',
                'verbose_name_plural': 'members',
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loan.member', verbose_name='Member'),
        ),
    ]
